### ISSUE TITLE
Stuck in "Please press reset button. ONLY FIRST TIME AFTER SERIAL LOAD!"

### ISSUE THREAD

**Issue by helgenodland** [SensorsIot/IOTAppstory.com#13]
**Can not get passed reset press.** 
Console print below, please help

Start IOTappStoryLoader V1.0

!!!!!!!!!!!!!!!  Please press reset button. ONLY FIRST TIME AFTER SERIAL LOAD!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!  Please press reset button. ONLY FIRST TIME AFTER SERIAL LOAD!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!  Please press reset button. ONLY FIRST TIME AFTER SERIAL LOAD!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Erasing Flash...
------------------ Writing Config --------------------------------
Stored NETGEAR11 
Mode: STA+AP
PHY mode: N
Channel: 6
AP id: 0
Status: 5
Auto connect: 1
SSID (9): NETGEAR11
Passphrase (12): waterytrain3
BSSID set: 0
After waiting 0.00 secs in setup() connection result is 3
Local ip: 10.0.29.5
setup done
Configuration portal requested
*WM: Scan done
*WM: Adding parameter
*WM: 
*WM: Adding parameter
*WM: boardName
*WM: Adding parameter
*WM: IOTappStory1
*WM: Adding parameter
*WM: IOTappStoryPHP1
*WM: Adding parameter
*WM: IOTappStory2
*WM: Adding parameter
*WM: IOTappStoryPHP2
*WM: SET AP STA
*WM: 
*WM: Configuring access point... 
*WM: INITloader
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Handle root

**Comment by SensorsIot** [comment]
You have now to connect with your smartphone to your ESP. It waits for you to type-in the credentials
