### ISSUE TITLE
Delay in debugPrint function

### ISSUE THREAD

**Issue by spagr** [SensorsIot/IOTAppstory.com#14]
Hello,
Thank You for this inspirational framework and Your ESP youtube videos too.
I have a question about debugging function "void debugPrint(char*txt, int nbr) " in ESP_helpers.h file, which have "delay(100);" instruction at the end. 
Is there any reason for that ?

Thank You in advance.

Martin

**Comment by SensorsIot** [comment]
I do not think so. Maybe a remaining line from testing... Anyway, only one has it.
