### ISSUE TITLE
New device added with MAC address, getting -104 error and no logs

### ISSUE THREAD

**Issue by lucaberta** [SensorsIot/IOTAppstory.com#21]
Hello @SensorsIot and @Onno-Dirkzwager 

I have started to play successfully with IOTAppstory.com last night, and the first tests done with a Wemos D1 mini and following the video have been successful.

Today I wanted to activate another board, this time a NodeMCU 1.0 board, and am running into issues.

Uploading the v1.1 loader, changing the configuration via the WiFi Manager, thus getting the board online with a DHCP address works well, and I can access the configuration and information page, where I recorded the MAC address of the NodeMCU ESP8266.

I configured a new device on the web frontend, created a new project and assigned the slow blink app to it, but then I run into an error when the loader connects to the OTA service. Here is the log:

*WM: Connection result: 
*WM: WL_CONNECTED
*WM: Handle root
*WM: Server Close
*WM: Sent server close page
Connected to WiFi... :-)
------------------ Writing Config --------------------------------
Stored xxxx
Going to IOTappStory.com
MAC: 5C:CF:7F:81:11:66
IP = 192.168.5.141

Updating Sketch from...
Update_server iotappstory.com
UPDATE_URL /ota/esp8266-v1.php
FIRMWARE_VERSION IOTappStoryLoader V1.1
SKETCH_UPDATE_FAILD Error (-104): Wrong HTTP code
Updating Sketch from...
Update_server iotappstory.com
UPDATE_URL /ota/esp8266-v1.php
FIRMWARE_VERSION IOTappStoryLoader V1.1
SKETCH_UPDATE_FAILD Error (-104): Wrong HTTP code

Updating SPIFFS from...
Update_server iotappstory.com
UPDATE_URL /ota/esp8266-v1.php
FIRMWARE_VERSION IOTappStoryLoader V1.1
SPIFFS_UPDATE_FAILD Error (-104): Wrong HTTP code
Returning from IOTAppstory

Configuration portal requested
*WM: Scan done

and then the logs are the ones for the configuration portal which starts again.

There are no relevant logs on the web frontend.

I did all the steps in the "troubleshooting" article on the Wiki but I could not solve the issue.

At the same time, I have tried to see if the Wemos board worked, and its connection to the OTA web service was correctly logged, so the system is correctly up and running on your side.

This issue can be easily replicated and happens all the time. I am available for any further debugging if needed.

Thanks, Luca

**Comment by lucaberta** [comment]
Issue resolved, it was a small yet difficult to spot error.

I mistakenly used the "Access point MAC" instead of the "Station MAC" from the Wifi Manager information page.

They look very much the same, as in my case they are:

Access Point MAC	5E:CF:7F:81:11:66
Station MAC	5C:CF:7F:81:11:66

so I was mistaken when I configured the device on the web frontend and put the AP MAC instead.

What is interesting is the fact that after having edited the device MAC address, all of a sudden *all* the log entries, including the events tried with the wrong MAC address, are now visible on the log.

This is a good lesson learned, and maybe the Troubleshooting Wiki page could be improved by adding this case with a wrong MAC address.

I will keep the issue open to see if you have any feedback, but you are free to close it when you want.

Thanks, Luca

**Comment by SensorsIot** [comment]
The advice is not to use the Mac address from WiFiManager, but from Serial Monitor. There is always the right one...
If you call with the wrong MAC address we do not know the owner of the device. It can belong to everybody and in your log, you only see your devices. But I will have a look at the Wiki. Maybe we have to be more clear about the case you find nothing in the log.
