### ISSUE TITLE
Download time

### ISSUE THREAD

**Issue by rgbetanco** [SensorsIot/IOTAppstory.com#3]
Hi, i just have a question. I used your library and everything seems to be ok, I get connected and the name of the new file is printed in the console and start printing dots but this process never finished, do you know why ? the files are on my server by the way

**Comment by SensorsIot** [comment]
Usually, this is if the ESP tries to connect the network. Did you enter the WiFi  credentials?

**Comment by rgbetanco** [comment]
Sorry, the previous issue is wrong, the dots appeared because the new software was already updated and it cannot connect.
