### ISSUE TITLE
Wifi parameters for stuff which needs the value before setup() loop

### ISSUE THREAD

**Issue by vyruz1986** [SensorsIot/IOTAppstory.com#8]
Hi,
As you requested in your video, I am trying to port an existing sketch I had (DHT22 MQTT temperature logger) to an IOTAppStory sketch.
I am running into something that I don't know the solution to:
For reading DHT22 sensors, I use the [adafruit DHT library](https://github.com/adafruit/DHT-sensor-library) which requires an instance of the library to be created before setup() function is run. 
The problem is when creating the instance you have to pass the pin number of the DHT sensors as a parameter, like so:
```c++
#define DHTPIN D4
#define DHTTYPE DHT22
DHT dht(DHTPIN, DHTTYPE);
```
Looking at the virginSoil code I started with, it seems I will never have my `config` struct variables at boot time, because the  `readFullConfiguration();` function is only called in the `setup()` loop

Is there a solution to this?

**Comment by SensorsIot** [comment]
This library is written for fixed pins and sensor types, which is understandable for me, because usually, you wire your device before you write/load the sketch. This is somehow different than credentials, or services you want to call. These things can change without physical change.
If you want to create a flexible script, you have to add a function to the library which is able to change the pin and sensor type on the fly. This is not very complicated.

**Comment by vyruz1986** [comment]
I figured it out:

You can do the following:
``` c++
byte bDHTPin = 0;
int iDHTType = 0;   //DHT type is a define which resolves to an int (DHT11 = 11, DHT22 = 22)
DHT dht(NULL, NULL);
```
the above snippet will ensure you have a `dht` object, albeit initialised with the incorrect pin and type.

Later on in the final part of `setup()`, when the wifi library has loaded the custom parameters from the setup page, you can assigned the real values like this:

``` c++
setup()
{
   bDHTPin = config.cDHTPin;   //config struct is filled with data from wifi setup page
   iDHTType = config.cDHTType;
   dht = DHT(bDHTPin, iDHTType);
}
```

This will re-initialise the object  with the correct values and make the rest of the sketch work fine.

Issue can be closed.

**Comment by SensorsIot** [comment]
Thanks for the tip. I learned something!
